# vim:fenc=utf-8 ff=unix ft=yaml :

version: "2"
services:
  app:
    build:
      context: "containers/app"
      dockerfile: "Dockerfile"
    volumes:
      - ".:/app"
      - "bundler-data:/usr/local/bundle"
      - "node_modules-data:/app/node_modules"
    ports:
      - "3000:3000"
    links:
      - db
    environment:
      DB_HOST: "db"
      DB_PORT: 5432
      DB_USER: "postgres"
      DB_PASS: ""
      DB_NAME: "inventist"
    tty: true
    stdin_open: true
    command: "rails s -b 0.0.0.0 -p 3000"
  db:
    build:
      context: "containers/db"
      dockerfile: "Dockerfile"
    volumes:
      - "db-data:/var/lib/postgresql/data"

volumes:
  bundler-data:
    driver: "local"
  node_modules-data:
    driver: "local"
  db-data:
    driver: "local"
